export const DOMAIN_MAP: Record<string, string> = {
  TCS: "tcs.com",
  RELIANCE: "ril.com",
  HDFCBANK: "hdfcbank.com",
  INFY: "infosys.com",
  SBIN: "sbi.co.in",
  ICICIBANK: "icicibank.com",
  ITC: "itcportal.com",
  LT: "larsentoubro.com",
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  GOOGL: "abc.xyz",
  GOOG: "abc.xyz",
  AMZN: "amazon.com",
  NVDA: "nvidia.com",
  META: "meta.com",
  TSLA: "tesla.com",
  JPM: "jpmorganchase.com",
  WMT: "walmart.com",
  BAC: "bankofamerica.com",
  V: "visa.com",
  MA: "mastercard.com",
  DMART: "avenuesupermarts.com",
  TITAN: "titancompany.in",
  ADANIENT: "adani.com",
  ADANIPORTS: "adaniports.com",
};
