export const CRYPTO_ICON_ID_MAP: Record<string, string> = {
  BTC: "bitcoin",
  ETH: "ethereum",
  USDT: "tether",
  BNB: "binancecoin",
  SOL: "solana",
  XRP: "ripple",
  USDC: "usd-coin",
  ADA: "cardano",
  DOGE: "dogecoin",
  TON: "the-open-network",
  TRX: "tron",
  DOT: "polkadot",
  MATIC: "matic-network",
  SHIB: "shiba-inu",
  LTC: "litecoin",
};

export const STOCK_DOMAIN_MAP: Record<string, string> = {
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  GOOGL: "abc.xyz",
  GOOG: "abc.xyz",
  AMZN: "amazon.com",
  NVDA: "nvidia.com",
  META: "meta.com",
  TSLA: "tesla.com",
  JPM: "jpmorganchase.com",
  WMT: "walmart.com",
  BAC: "bankofamerica.com",
  V: "visa.com",
  MA: "mastercard.com",
  RELIANCE: "ril.com",
  TCS: "tcs.com",
  INFY: "infosys.com",
  HDFCBANK: "hdfcbank.com",
  ICICIBANK: "icicibank.com",
  ITC: "itcportal.com",
  LT: "larsentoubro.com",
  SBIN: "sbi.co.in",
  DMART: "avenuesupermarts.com",
  TITAN: "titancompany.in",
  ADANIENT: "adani.com",
  ADANIPORTS: "adaniports.com",
};

export const EXCHANGE_ICON_MAP: Record<string, string> = {
  NASDAQ: "https://logo.clearbit.com/nasdaq.com",
  NYSE: "https://logo.clearbit.com/nyse.com",
  NYSEARCA: "https://logo.clearbit.com/nyse.com",
  NSE: "https://logo.clearbit.com/nseindia.com",
  BSE: "https://logo.clearbit.com/bseindia.com",
  FOREX: "https://logo.clearbit.com/oanda.com",
  FX: "https://logo.clearbit.com/oanda.com",
  BINANCE: "https://logo.clearbit.com/binance.com",
  GLOBAL: "https://logo.clearbit.com/coingecko.com",
  SP: "https://logo.clearbit.com/spglobal.com",
  DJ: "https://logo.clearbit.com/dowjones.com",
  LSE: "https://logo.clearbit.com/londonstockexchange.com",
  XETRA: "https://logo.clearbit.com/deutsche-boerse.com",
  EURONEXT: "https://logo.clearbit.com/euronext.com",
  TSE: "https://logo.clearbit.com/jpx.co.jp",
  HKEX: "https://logo.clearbit.com/hkex.com.hk",
};
